/**
 * Asset normalisation pipeline.
 *
 * Reads the untouched original drop from `assets-source/`, and writes optimised
 * masters into `public/images/<section>/<kebab-case-name>.{avif,webp}`.
 *
 * Only ONE master per image is produced, at native resolution. Responsive
 * widths are generated by the Next.js image optimiser from that master at
 * build/request time — see docs/decisions.md (ADR-006). Pre-generating fixed
 * width derivatives here would duplicate that work and add megabytes to the
 * repository for no delivered benefit.
 *
 * Usage:
 *   node scripts/optimize-assets.mjs            # write masters
 *   node scripts/optimize-assets.mjs --preview  # also write small previews to .preview/
 *   node scripts/optimize-assets.mjs --check    # report only, write nothing
 */

import { mkdir, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import sharp from 'sharp';

const ROOT = path.resolve(import.meta.dirname, '..');
const SOURCE_DIR = path.join(ROOT, 'assets-source', 'images');
const OUTPUT_DIR = path.join(ROOT, 'public', 'images');
const PREVIEW_DIR = path.join(ROOT, '.preview');

const AVIF_OPTIONS = { quality: 55, effort: 6, chromaSubsampling: '4:2:0' };
const WEBP_OPTIONS = { quality: 82, effort: 5 };

/**
 * Maps an original source folder + filename onto its normalised section and
 * target basename. Every original in the drop must match exactly one rule;
 * an unmatched file is a hard error rather than a silent skip.
 */
const RULES = [
  {
    match: /1\.Mining & Extraction\/1\.Open-Pit-Quarry\.png$/,
    section: 'extraction',
    name: 'open-pit-quarry',
  },
  {
    match: /1\.Mining & Extraction\/2\.Underground-Mining\.png$/,
    section: 'extraction',
    name: 'underground-mining',
  },
  {
    match: /2\.Processing & Manufacturing\/1\.Kiln-&-Plant\.png$/,
    section: 'processing',
    name: 'kiln-and-plant',
  },
  {
    match: /2\.Processing & Manufacturing\/2\.Grinding-Mills-&-Micronizers\.png$/,
    section: 'processing',
    name: 'grinding-mills-and-micronizers',
  },
  {
    match: /2\.Processing & Manufacturing\/3\.Powder-Texture\.png$/,
    section: 'product',
    name: 'caco3-powder-mound',
  },
  {
    match: /3\.Quality Control & Lab\/1\.Lab-&-QC-Testing\.png$/,
    section: 'quality',
    name: 'lab-and-qc-testing',
  },
  {
    match: /4\.Industrial Applications\/1\.Plastics-&-Masterbatch\.png$/,
    section: 'applications',
    name: 'plastics-and-masterbatch',
  },
  {
    match: /4\.Industrial Applications\/2\.Paints-&-Coatings\.png$/,
    section: 'applications',
    name: 'paints-and-coatings',
  },
  {
    match: /4\.Industrial Applications\/3\.Oil-&-Gas-Drilling\.png$/,
    section: 'applications',
    name: 'oil-and-gas-drilling',
  },
  {
    match: /4\.Industrial Applications\/4\.Paper-&-Packaging\.png$/,
    section: 'applications',
    name: 'paper-and-paperboard',
  },
  {
    match: /5\.Packaging & Logistics\/1\.Paper-Valve-Bags-on-Pallets\.png$/,
    section: 'packaging',
    name: 'paper-valve-bags-on-pallets',
  },
  {
    match: /5\.Packaging & Logistics\/2\.Jumbo-Bags-Storage\.png$/,
    section: 'packaging',
    name: 'jumbo-bags-storage',
  },
  {
    match: /5\.Packaging & Logistics\/3\.Bulk-Silo-Tanker-Truck\.png$/,
    section: 'packaging',
    name: 'bulk-silo-tanker-truck',
  },
];

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walk(full)));
    } else if (/\.(png|jpe?g|tiff?|webp)$/i.test(entry.name)) {
      files.push(full);
    }
  }
  return files.sort();
}

function resolveRule(sourcePath) {
  const relative = path.relative(SOURCE_DIR, sourcePath).split(path.sep).join('/');
  const rule = RULES.find((candidate) => candidate.match.test(relative));
  if (!rule) {
    throw new Error(
      `No normalisation rule for "${relative}". Add a rule to scripts/optimize-assets.mjs — ` +
        `an unclassified asset must never be silently skipped.`,
    );
  }
  return { ...rule, relative };
}

async function main() {
  const argv = new Set(process.argv.slice(2));
  const checkOnly = argv.has('--check');
  const withPreview = argv.has('--preview');

  const sources = await walk(SOURCE_DIR);
  if (sources.length === 0) {
    throw new Error(`No source images found under ${SOURCE_DIR}`);
  }

  const report = [];

  for (const source of sources) {
    const rule = resolveRule(source);
    const image = sharp(source);
    const meta = await image.metadata();
    const original = await stat(source);

    const targetDir = path.join(OUTPUT_DIR, rule.section);
    const avifPath = path.join(targetDir, `${rule.name}.avif`);
    const webpPath = path.join(targetDir, `${rule.name}.webp`);

    if (!checkOnly) {
      await mkdir(targetDir, { recursive: true });
      await sharp(source).avif(AVIF_OPTIONS).toFile(avifPath);
      await sharp(source).webp(WEBP_OPTIONS).toFile(webpPath);
    }

    if (withPreview && !checkOnly) {
      await mkdir(PREVIEW_DIR, { recursive: true });
      await sharp(source)
        .resize({ width: 960 })
        .webp({ quality: 70 })
        .toFile(path.join(PREVIEW_DIR, `${rule.section}--${rule.name}.webp`));
    }

    const avifSize = checkOnly ? 0 : (await stat(avifPath)).size;
    const webpSize = checkOnly ? 0 : (await stat(webpPath)).size;

    report.push({
      source: `assets-source/images/${rule.relative}`,
      avif: path.relative(ROOT, avifPath).split(path.sep).join('/'),
      webp: path.relative(ROOT, webpPath).split(path.sep).join('/'),
      section: rule.section,
      width: meta.width,
      height: meta.height,
      originalBytes: original.size,
      avifBytes: avifSize,
      webpBytes: webpSize,
    });
  }

  const totalOriginal = report.reduce((sum, row) => sum + row.originalBytes, 0);
  const totalAvif = report.reduce((sum, row) => sum + row.avifBytes, 0);
  const totalWebp = report.reduce((sum, row) => sum + row.webpBytes, 0);

  for (const row of report) {
    const mb = (bytes) => (bytes / 1024 / 1024).toFixed(2).padStart(7);
    console.log(
      `${mb(row.originalBytes)}MB -> avif ${mb(row.avifBytes)}MB / webp ${mb(row.webpBytes)}MB  ${row.avif}`,
    );
  }
  console.log(
    `\n${report.length} assets. original ${(totalOriginal / 1024 / 1024).toFixed(1)}MB ` +
      `-> avif ${(totalAvif / 1024 / 1024).toFixed(1)}MB, webp ${(totalWebp / 1024 / 1024).toFixed(1)}MB`,
  );

  if (!checkOnly) {
    await writeFile(
      path.join(ROOT, 'docs', 'asset-optimization-report.json'),
      `${JSON.stringify({ generatedBy: 'scripts/optimize-assets.mjs', assets: report }, null, 2)}\n`,
      'utf8',
    );
  }
}

await main();
