// Separate art direction for the overview and each destination page.
export const pageImages={about:'about-hero',contact:'contact-hero',consultation:'consultation-hero'};
export const homeImages={'industrial-solutions':'industrial-overview',mining:'mining-overview','solar-thermal-energy':'solar-overview',consultation:'consultation'};
export const journeyImages={
  mineral:['process-source','process-granules','journey','particle-study','application-materials','consultation-hero'],
  mining:['mining','mining-overview','process-source','process-granules','particle-study','application-materials'],
  solar:['solar','solar-overview','industrial-overview','thermal-storage','industrial'],
};
export const newAlts={
 en:{'industrial-overview':'Cutaway study of a shell-and-tube heat exchanger with a navy flange','mining-overview':'Limestone drill core specimens arranged for geological examination','solar-overview':'Close detail of a curved solar thermal mirror and absorber pipe','consultation-hero':'Precision caliper, mineral samples and geometric technical drawings','about-hero':'Architectural arrangement of limestone, layered rock and stainless steel samples','contact-hero':'Sunlight across limestone fins and a curved stone architectural detail','process-source':'Natural fractured limestone specimen showing grain and fine mineral seams','process-granules':'Crushed white limestone fractions arranged in stainless sample channels','particle-study':'Illustrative magnified study of irregular ground calcium carbonate particles','thermal-storage':'Conceptual insulated thermal tanks, pipework and heat exchanger','application-materials':'Limestone alongside a polymer pipe, paper roll and coated panel'},
 ar:{'industrial-overview':'مقطع توضيحي لمبادل حراري أنبوبي مع وصلة بلون أزرق داكن','mining-overview':'عينات أسطوانية من الحجر الجيري مرتبة للفحص الجيولوجي','solar-overview':'تفصيل لمرآة شمسية حرارية منحنية وأنبوب امتصاص الحرارة','consultation-hero':'قدمة قياس دقيقة وعينات معدنية ورسومات هندسية','about-hero':'تكوين معماري من عينات الحجر الجيري والصخر الطبقي والفولاذ','contact-hero':'ضوء الشمس على عناصر حجر جيري وتفصيل معماري حجري منحني','process-source':'عينة حجر جيري طبيعي متكسر تظهر الحبيبات والعروق المعدنية الدقيقة','process-granules':'أجزاء من الحجر الجيري الأبيض المكسر في قنوات عينات معدنية','particle-study':'تصوّر مكبّر لجسيمات غير منتظمة من كربونات الكالسيوم المطحونة','thermal-storage':'تصوّر لخزانات حرارية معزولة وأنابيب ومبادل حراري','application-materials':'حجر جيري بجوار أنبوب بوليمري ولفافة ورق ولوح مطلي'}
};
